# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-09-23 13:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20190109_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abusereport',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='abusereport',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='basket_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name_local',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ircname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_full_name_local',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_ircname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_tshirt',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='referral_source',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tshirt',
        ),
        migrations.DeleteModel(
            name='AbuseReport',
        ),
    ]
