# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-09-25 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20200923_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='geo_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='geo_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='geo_region',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_geo_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_geo_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_geo_region',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_region',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_story_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_timezone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='story_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='title',
        ),
        migrations.AlterField(
            model_name='externalaccount',
            name='type',
            field=models.CharField(max_length=30, verbose_name='Account Type'),
        ),
    ]
