# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-09-25 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20200925_0405'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='language',
            name='userprofile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_languages',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
