# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-09-28 14:25
from __future__ import unicode_literals

from django.db import migrations


def remove_unvouched(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.filter(userprofile__is_vouched=False).delete()
    User.objects.filter(userprofile__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20200925_0647'),
    ]

    operations = [
        migrations.RunPython(remove_unvouched)
    ]
