# Generated by Django 2.2.16 on 2020-09-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_remove_unvouched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idpprofile',
            name='auth0_user_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='idpprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='idpprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown Provider'), (10, 'Passwordless Provider'), (20, 'Google Provider'), (30, 'Github Provider'), (31, 'Firefox Accounts Provider'), (40, 'LDAP Provider')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='idpprofile',
            name='username',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='auth0_user_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_vouch',
            field=models.BooleanField(default=False, help_text='You can edit can_vouch status by editing invidual vouches'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_mozillian',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='When was involved with Mozilla'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_vouched',
            field=models.BooleanField(default=False, help_text='You can edit vouched status by editing invidual vouches'),
        ),
        migrations.AlterField(
            model_name='vouch',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='Reason for Vouching'),
        ),
    ]
