# Generated by Django 2.2.16 on 2020-09-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozspaces', '0011_auto_20200929_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mozspace',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='mozspace',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='mozspace',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='MozSpace',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
