# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-09-24 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_auto_20171206_0641'),
        ('users', '0046_auto_20200923_0630'),
    ]

    operations = [
        migrations.RunSQL(
            """
                drop table groups_groupmembership;
                drop table groups_groupalias;
                drop table groups_group_curators;
                drop table groups_invite;
                drop table groups_group;
                drop table groups_skillalias;
                drop table groups_skill;
            """,
            state_operations=[
                migrations.RemoveField(
                    model_name='group',
                    name='curators',
                ),
                migrations.RemoveField(
                    model_name='group',
                    name='invites',
                ),
                migrations.RemoveField(
                    model_name='groupalias',
                    name='alias',
                ),
                migrations.AlterUniqueTogether(
                    name='groupmembership',
                    unique_together=set([]),
                ),
                migrations.RemoveField(
                    model_name='groupmembership',
                    name='group',
                ),
                migrations.RemoveField(
                    model_name='groupmembership',
                    name='userprofile',
                ),
                migrations.AlterUniqueTogether(
                    name='invite',
                    unique_together=set([]),
                ),
                migrations.RemoveField(
                    model_name='invite',
                    name='group',
                ),
                migrations.RemoveField(
                    model_name='invite',
                    name='inviter',
                ),
                migrations.RemoveField(
                    model_name='invite',
                    name='redeemer',
                ),
                migrations.RemoveField(
                    model_name='skillalias',
                    name='alias',
                ),
                migrations.DeleteModel(
                    name='Group',
                ),
                migrations.DeleteModel(
                    name='GroupAlias',
                ),
                migrations.DeleteModel(
                    name='GroupMembership',
                ),
                migrations.DeleteModel(
                    name='Invite',
                ),
                migrations.DeleteModel(
                    name='Skill',
                ),
                migrations.DeleteModel(
                    name='SkillAlias',
                ),
            ]
        )
    ]
