# Generated by Django 2.2.16 on 2020-09-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='mapbox_id',
            field=models.CharField(help_text="'id' field from Mapbox", max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='name field from Mapbox', max_length=120),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(help_text='lowercased 2-letter code from Mozilla product data', max_length=2),
        ),
        migrations.AlterField(
            model_name='country',
            name='mapbox_id',
            field=models.CharField(help_text="'id' field from Mapbox", max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='name field from Mapbox', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='mapbox_id',
            field=models.CharField(help_text="'id' field from Mapbox", max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='name field from Mapbox', max_length=120),
        ),
    ]
