# Generated by Django 2.2.16 on 2020-09-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20200929_0509'),
        ('users', '0050_auto_20200929_0509')
    ]

    operations = [
        migrations.RunSQL(
            """
                drop table geo_city;
                drop table geo_region;
                drop table geo_country;
            """,
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='region',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='region',
                    name='country',
                ),
                migrations.DeleteModel(
                    name='City',
                ),
                migrations.DeleteModel(
                    name='Country',
                ),
                migrations.DeleteModel(
                    name='Region',
                ),
            ]
        )
    ]
