# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-09-25 11:05


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20160307_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='redeemer',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
