# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-09-23 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171020_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiv2app',
            name='owner',
        ),
        migrations.DeleteModel(
            name='APIv2App',
        ),
    ]
